# Generated by Django 5.1.3 on 2024-12-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
                ('creator', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
